# hello-go task-build.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: hello-go

outputs:
- name: dist

run:
  path: ./hello-go/ci/scripts/build.sh
