resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
- name: github-status
  type: docker-image
  source:
    repository: dpb587/github-status-resource
    tag: master

resources:
- name: hello-go
  type: git
  source:
    uri: https://github.com/jeffdecola/hello-go
    branch: master
- name: resource-dump-to-dockerhub
  type: docker-image
  source:
    repository: concourse/git-resource
    username: jeffdecola
    password: {{dockerhub_password}}
- name: resource-slack-alert
  type: slack-notification
  source:
    url: {{slack_url}} 
- name: resource-repo-status 
  type: github-status
  source:
    repository: jeffdecola/hello-go 
    access_token: {{repo_github_token}}

jobs:
- name: job-test-app-hello
  plan:
    - get: hello-go
      trigger: true
    - task: task-unit-tests
      file: hello-go/ci/tasks/task-unit-tests.yml

- name: job-build
  plan:
    - get: hello-go
      trigger: true
      passed: [job-test-app-hello]
    - put: resource-repo-status
      params: { state: "pending", commit: "hello-go" }
    - task: task-build
      file: hello-go/ci/tasks/task-build.yml
    - put: resource-dump-to-dockerhub
      params: {build: hello-go}
      on_success:
        put: resource-repo-status
        params: { state: "success", commit: "hello-go" }
        ensure:
          put: resource-slack-alert
          params:
            channel: '#general'
            text: |
            From hello-go: This works great!
      on_failure:
        put: resource-repo-status
        params: { state: "failure", commit: "hello-go" }
        ensure:
          put: resource-slack-alert
          params:
            channel: '#general'
            text: |
              From hello-go: Something went wrong. This stinks!
