resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: hello-go
  type: git
  source:
    uri: https://github.com/jeffdecola/hello-go
    branch: master
- name: resource-slack-alert
  type: slack-notification
  source:
    url: {{slack_url}} 

jobs:
- name: job-test-app-hello
  plan:
  - get: hello-go
    trigger: true
  - task: task-unit-tests
    file: hello-go/task-build.yml
    on_success:
      put: resource-slack-alert
      params:
        channel: '#general'
        text: |
          From hello-go: This works great!
    on_failure:
      put: resource-slack-alert
      params:
        channel: '#general'
        text: |
          From hello-go: Something went wrong!
