resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resource_types:
  - name: github-status
    type: docker-image
    source:
      repository: "dpb587/github-status-resource"
      tag: master

resources:
- name: hello-go
  type: git
  source:
    uri: https://github.com/jeffdecola/hello-go
    branch: master
- name: resource-slack-alert
  type: slack-notification
  source:
    url: {{slack_url}} 
- name: resoruce-repo-status 
  type: github-status
    source:
      repository: https://github.com/jeffdecola/hello-go 
      access_token: {{repo_github_token}}

jobs:
- name: job-test-app-hello
  plan:
  - get: hello-go
    trigger: true
  - put: resoruce-repo-status
      params: { state: "pending", commit: "repo" }
  - task: task-unit-tests
    file: hello-go/task-build.yml
    on_success:
      - put: resoruce-repo-status
        params: { state: "success", commit: "repo" }
      - put: resource-slack-alert
        params:
          channel: '#general'
          text: |
            From hello-go: This works great!
    on_failure:
      - put: resoruce-repo-status
        params: { state: "failure", commit: "repo" }
      - put: resource-slack-alert
        params:
          channel: '#general'
          text: |
            From hello-go: Something went wrong!
