# hello-go pipeline

jobs:
- name: job-test-app-hello
  plan:
    - get: hello-go
      trigger: true
    - put: resource-slack-alert
      params:
        channel: '#jeff-builds'
        text: "From hello-go: Starting hello-go in concourse."
    - put: resource-repo-status
      params: { state: "pending", commit: "hello-go" }
    - task: task-unit-tests
      file: hello-go/ci/tasks/task-unit-tests.yml

- name: job-build
  plan:
    - get: hello-go
      trigger: true
      passed: [job-test-app-hello]
    - put: resource-dump-to-dockerhub
      params: {build: dist}
    - task: task-build
      file: hello-go/ci/tasks/task-build.yml
      on_success:
        do:
        - put: resource-repo-status
          params: { state: "success", commit: "hello-go" }
        - put: resource-slack-alert
          params:
            channel: '#jeff-builds'
            text: "From hello-go: This works great!"
      on_failure:
        do:
        - put: resource-repo-status
          params: { state: "failure", commit: "hello-go" }
        - put: resource-slack-alert
          params:
            channel: '#jeff-builds'
            text: "From hello-go: Something went wrong. This stinks!"

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
- name: github-status
  type: docker-image
  source:
    repository: dpb587/github-status-resource
    tag: master

resources:
- name: hello-go
  type: git
  source:
    uri: https://github.com/jeffdecola/hello-go
    branch: master
- name: resource-dump-to-dockerhub
  type: docker-image
  source:
    repository: jeffdecola/hello-go
    tag: latest
    username: jeffdecola
    password: {{dockerhub_password}}
- name: resource-slack-alert
  type: slack-notification
  source:
    url: {{slack_url}} 
- name: resource-repo-status 
  type: github-status
  source:
    repository: jeffdecola/hello-go 
    access_token: {{repo_github_token}}

